name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good
    
    - name: Install buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.33
        pip install buildozer==1.4.0
        pip install virtualenv
    
    - name: Accept Android licenses
      run: |
        yes | buildozer android update
    
    - name: Build APK
      run: |
        yes | buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0
        ANDROID_SDK_ACCEPT_LICENSES: 1
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ticofit-debug
        path: bin/*.apk
        if-no-files-found: warn
